# Generated by Django 4.1.7 on 2023-03-08 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('grade', models.PositiveIntegerField()),
                ('specialty', models.CharField(max_length=50)),
                ('salary', models.PositiveIntegerField()),
                ('education', models.TextField()),
                ('experience', models.IntegerField()),
                ('portfolio', models.URLField()),
                ('title', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=16)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
